version: "3.6"
services:
  client:
    build: ds-template-angular/
    container_name: ds-app-client
    image: ds_app_client
    environment:
      - NODE_ENV=development
      - ANGULAR_APP_SERVER_HOST=http://localhost:3000
    ports:
      - 4200:4200
    volumes:
      - "./ds-template-angular/:/app"
  server:
    build: ds-template-spring/
    container_name: ds-app-server
    image: ds_app_server
    ports:
      - 8080:8080
    volumes:
      - "./ds-template-spring/:/app"
volumes:
  ? data
