version: "3.6"
services:
  client:
    build: ds-template-angular/
      # context: ./ds-template-angular/
      # dockerfile: Dockerfile
    container_name: ds-app-client
    image: ds_app
    environment:
      - NODE_ENV=development
      - ANGULAR_APP_SERVER_HOST=http://localhost:3000
    ports:
      - 4200:4200
    volumes:
      - "./ds-template-angular/:/app"
volumes:
  ? data

  # docker run -d --name nba-app-server -p 80:80 -v `pwd`/data/db.json:/data/db.json clue/json-server